[package]
name = "infrastructure"
version = "0.1.0"
edition = "2024"

[dependencies]
domain = { workspace = true }

sea-orm = { workspace = true, features = [
    "sqlx-postgres",
    "runtime-tokio",
    "macros",
    "mock",
    "with-time",
] }
sea-orm-migration = { workspace = true }
time = { workspace = true }
# 数据库迁移顺序比较重要，还是显示设置比较好
#inventory = { workspace = true }