[server]
host = "0.0.0.0"
port = 4000
request_timeout_seconds = 30
max_body_size_mb = 2
cors_origins = ["http://localhost:3000"]

[database]
url = "postgres://postgres:root@localhost:5432/postgres"
max_connections = 100
min_connections = 5

[log]
# 以下配置均可省略，使用代码默认值
# file_log_enable = true
# log_path = "logs"
# name_prefix = "{{project-name}}.log"
# timezone_offset = 8
